# Note: It requires docker-compose 1.13.0
# origin file: https://github.com/budtmo/docker-android/blob/master/docker-compose.yml#L70
#
# Usage: docker-compose up -d
version: "3"

networks:
  apitest:

services:
  db:
    container_name: database_container
    image: postgres
    restart: always
    ports:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - apitest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: apitestspark

  api:
    container_name: api_container
    image: seabath/sparktestapi:latest
    depends_on:
      - db
    ports:
      - 4567:4567
    networks:
      - apitest
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_URL: database_container:5432/apitestspark
